export const SERVER_STATUS={
	STATUS_CODE_OK: 200,
	STATUS_CODE_BAD_REQUEST:400,
	STATUS_CODE_RESOURCE_NOT_FOUND:404,
	STATUS_CODE_METHOD_NOT_ALLOWED:405,
	STATUS_CODE_CONFLICT:409,
	STATUS_CODE_INTERNAL_SERVER_ERROR:500,
};
